language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: marcojrfurtado
  password:
    secure:
  on:
    tags: true
    repo: marcojrfurtado/osmosis-streaming-driver
    python: 3.7
